### ISSUE TITLE
Shutdown issue in integration tests

### ISSUE THREAD

**Issue by martinschaef** [MagpieBridge/MagpieBridge#37]
We are writing some integration tests for our server, but it looks like the shutdown is not implemented [here](https://github.com/MagpieBridge/MagpieBridge/blob/6b5dc1599cfe49e02f287457e3902bd485877fbd/src/main/java/magpiebridge/core/MagpieServer.java#L356-L359).

This causes our tests to exhibit all sorts of unexpected behavior because suddenly multiple servers are running.

**Comment by jonasmanuel** [comment]
According to the spec, a shutdown notifies the server that it should expect to shutdown, 
but antoher call to 'exit' is expected to actually turn the server off.

https://microsoft.github.io/language-server-protocol/specification#shutdown

**Comment by martinschaef** [comment]
Ah ... but I can't call exit from an integration test because the System.exit would kill my test.

Also, just closing the socket would not be sufficient if we launched with launchOnStream, right?
Currently, we get the following stack trace if two integration tests launch servers:

```
lspintegration.analysis.RunnerTest > test_multipleFindingsWithJarsFolder() FAILED
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
        at java.util.ArrayList$Itr.next(ArrayList.java:859)
        at soot.SootResolver.bringToSignaturesUnchecked(SootResolver.java:305)
        at soot.SootResolver.bringToSignatures(SootResolver.java:298)
        at soot.SootResolver.processResolveWorklist(SootResolver.java:162)
        at soot.SootResolver.resolveClass(SootResolver.java:141)
        at soot.Scene.tryLoadClass(Scene.java:979)
        at soot.Scene.loadBasicClasses(Scene.java:1708)
        at soot.Scene.loadNecessaryClasses(Scene.java:1807)
        at magpiebridge.converter.WalaToSootIRConverter.initializeSoot(WalaToSootIRConverter.java:237)
        at magpiebridge.converter.WalaToSootIRConverter.<init>(WalaToSootIRConverter.java:102)
        at magpiebridge.converter.WalaToSootIRConverter.<init>(WalaToSootIRConverter.java:129)
        at magpiebridge.converter.WalaToSootIRConverter.<init>(WalaToSootIRConverter.java:84)
        at ...
```

**Comment by jonasmanuel** [comment]
you could start a separate vm if you are communicating through stdio... I don't know if that works for your integration tests though

**Comment by linghuiluo** [comment]
@martinschaef So you used launchOnStdio for two different integration tests? How many servers and clients did you create for these two tests? If one server is used for two clients in different tests, you could overwrite shutdown by clearing the states (all attributes are protected) of the server.

**Comment by martinschaef** [comment]
Two tests created one server each, and one test created two servers.

We start them on Streams. If both run on the same stream, bad things will probably happen, but at least between tests, I'd like to be able to shut them down properly. 

Is the System.exit really necessary? In my opinion, System.exit always leads to problems down the road and should really only be used in the main to signal error codes.

**Comment by linghuiluo** [comment]
@martinschaef shutdown doesn't need to exit, as defined in the protocol. System.exit is only used in the exit method as shown below.

https://github.com/MagpieBridge/MagpieBridge/blob/6b5dc1599cfe49e02f287457e3902bd485877fbd/src/main/java/magpiebridge/core/MagpieServer.java#L367-L377

The current shutdown in MagpieBridge does nothing. One can easily override it and clear the fields. So does the exit method.

**Comment by linghuiluo** [comment]
The reason we didn't implement it is: to leave the users of MapgieBridge to define the way they would like to have it.

**Comment by linghuiluo** [comment]
If you are using soot, when you overrides shutdown method, better call G.v().reset() because of all the singletons used in soot.

**Comment by linghuiluo** [comment]
@jcp19 Did you ask the same issue in #38? Can we close this one now? As @jonasmanuel mentioned, you can create two instances of jvm for different integration tests using https://docs.oracle.com/javase/7/docs/api/java/lang/ProcessBuilder.html for example.

**Comment by jcp19** [comment]
Yes, that was the same issue I was facing
