### ISSUE TITLE
Proper shutdown of a MagpieServer

### ISSUE THREAD

**Issue by jcp19** [MagpieBridge/MagpieBridge#38]
Hey there 😃 
it looks to me that when a MagpieServer is launched, there is no clear way to shut it down and release the allocated resources. In particular, the `shutdown` method does not seem to be actually implemented.

https://github.com/MagpieBridge/MagpieBridge/blob/6b5dc1599cfe49e02f287457e3902bd485877fbd/src/main/java/magpiebridge/core/MagpieServer.java#L357-L359

Is there any way to do that?

**Comment by linghuiluo** [comment]
You could subclass the MagpieServer and overrides shutdown. All fields of MagpieServer are visible to subclasses.

**Comment by jcp19** [comment]
Yes, that's true. Thank you 👍
