### ISSUE TITLE
Displaying analysis results (computed invariants) for active program points

### ISSUE THREAD

**Issue by vesalvojdani** [MagpieBridge/MagpieBridge#67]
MagPie has worked great [for us](https://github.com/goblint/GobPie) so far, so this is more of a long-term wish, but I also believe you mentioned in some presentation that something like this might be planned. So what are the possibilities for selectively showing what an analyzer has computed for each program point? Is this already possible in MagPie? 

Ideally, one would somehow integrate with the IDEs tree-view or even mimic the way they display state of the program when debugging. These may be too IDE-specific to generalize in MagPie though. Minimally, one would need some way to update a (e.g., HTML) view based on the line in the program that the user has selected.

If this isn't currently possible, it would be nice to know what your plans are around this. I think we could also contribute to making this happen if it isn't in your immediate plans. Thank you! :)

**Comment by linghuiluo** [comment]
Hi @vesalvojdani , thanks for your interest!

"So what are the possibilities for selectively showing what an analyzer has computed for each program point? Is this already possible in MagPie?"

Hi, this can be encoded as a list of code actions in the AnalysisResult https://github.com/MagpieBridge/MagpieBridge/blob/8cbbd5a3657327449db02dff08a27bdd41279ac1/src/main/java/magpiebridge/core/AnalysisResult.java#L72 
or you can have a customized web interface (https://github.com/secure-software-engineering/secucheck is a good example using MagpieBridge, here is a video showing how the web interface looks like https://www.youtube.com/watch?v=6_GYxLu5Ay4)

"Ideally, one would somehow integrate with the IDEs tree-view or even mimic the way they display state of the program when debugging. "
We are currently developing support of visualizing data-flow path in a web view that can be displayed in many IDEs (e.g. https://code.visualstudio.com/api/extension-guides/webview). A student is developing this feature under the pull request:  https://github.com/MagpieBridge/MagpieBridge/pull/66
I am not sure if this is what you would like to have, below is a screenshot of our web view looks like. 
![image](https://user-images.githubusercontent.com/18470909/137462707-63abe258-d9ae-4eb7-8ce9-5fc4dc183ba8.png)

**Comment by vesalvojdani** [comment]
Okay, we will look into this... seems like this could do the trick. We're more interested in basic warnings at the moment, but I wanted to know what possibilities exist for displaying the full analysis results (for debugging the analyzer). I'll keep an eye on the mentioned pull request as well. Thanks again!
