### ISSUE TITLE
WalaIRToJimpleConverter: Variables generated for if-conditions have wrong type

### ISSUE THREAD

**Issue by SvenEV** [MagpieBridge/MagpieBridge#7]
For if-statements, Jimple code is generated that declares intermediary variables of the wrong type. In the example below, observe how locals of type `String`, `int` and `double` are declared, even though all of them should be of type `boolean`.

**Java code:**
```Java
public static void repro() {
    if ("A" == "B")
        return;

    if (5 < 3)
        return;

    if (5.0 < 3.0)
        return;
}
```

**Jimple code:**
```Java
public static void repro()
{
    java.lang.String $r0;
    int $i0;
    double $d0;
    $r0 = "A" == "B";
    if $r0 == 0 goto label1;
    return;
    label1:
    $i0 = 5 < 3;
    if $i0 == 0 goto label2;
    return;
    label2:
    $d0 = 5.0 < 3.0;
    if $d0 == 0 goto [?= null];
    return;
}
```

**Comment by SvenEV** [comment]
Note: I *think* this bug got introduced in yesterdays changes

**Comment by linghuiluo** [comment]
ok, i will try to fix it in the next days. Thanks for reporting

**Comment by linghuiluo** [comment]
fix.
