### ISSUE TITLE
Null passed as uri parameter to PublishDiagnosticsParams constructor

### ISSUE THREAD

**Issue by karoliineh** [MagpieBridge/MagpieBridge#73]
### Describe the bug

When renaming or deleting a file that contained an AnalysisResult, `null` is passed as an argument for the `uri` parameter when calling `public PublishDiagnosticsParams(@NonNull final String uri, @NonNull final List<Diagnostic> diagnostics)` method in `MagpieServer.cleanup()` method. This is probably due to the `String clientUri = null;` field in the `MagpieServer.getClientUri(String serverUri)` method. The `clientUri` stays `null`, because in case the `if (file.exists())` evaluates to false, then the `clientUri` value is not updated and the method returns its initial value, which is `null`.

**Possible fix**: The URL should be removed from the `Map<URL, List<Diagnostic>> diagnostics` map in `MagpieServer` class when deleted or renamed. I guess handling the `clientUri` variable in `MagpieServer.getClientUri(String serverUri)` method so that `null` would never be passed as uri to the `PublishDiagnosticsParams` constructor would probably be smart to do as well.

### To Reproduce

This can be reproduced on the [Demoproject ](https://github.com/MagpieBridge/DemoProject) with the [Tutorial 1](https://github.com/MagpieBridge/Tutorial1) extension:
1. build and install the extension
2. open Demoproject in VSCode and wait for the analysis to finish (works and displays the analysis result)

**With renaming**:

3. rename `Main.java` file and class
4. save the file again to trigger a new analysis (does not work and runs into an exception)

**With deleting**:

3. Create a new file e.g. `MainTwo.java` with the same main method as in `Main.java`
4. Save the file to trigger an analysis (works and displays the analysis result)
5. Delete the file and save the `Main.java` file to trigger an analysis (does not work and runs into an exception)

**Part of the exception description**: 
```
...
Caused by: java.lang.IllegalArgumentException: Property must not be null: uri
	at org.eclipse.lsp4j.util.Preconditions.checkNotNull(Preconditions.java:29)
	at org.eclipse.lsp4j.PublishDiagnosticsParams.<init>(PublishDiagnosticsParams.java:45)
	at magpiebridge.core.MagpieServer.cleanUp(MagpieServer.java:792)
	at magpiebridge.core.MagpieTextDocumentService.runAnalysis(MagpieTextDocumentService.java:143)
	at magpiebridge.core.MagpieTextDocumentService.didSave(MagpieTextDocumentService.java:137)
	... 16 more
```

NB! There is an unrelated exception thrown sometimes when analysing the [Demoproject ](https://github.com/MagpieBridge/DemoProject) with the [Tutorial 1](https://github.com/MagpieBridge/Tutorial1) extension. 

**Part of the exception description**: 
```
[Thread-10] ERROR heros.solver.CountingThreadPoolExecutor - Worker thread execution failed: null
java.util.ConcurrentModificationException
...
```

### Expected behaviour
In case of renaming or deleting a file, the extension should stay operational.

### Additional context

**OS:** Linux

**IDE:** VSCode

The behaviour is the same with the [GobPie](https://github.com/goblint/GobPie) project I am currently working on and reproducible the same way as in Tutorial 1. Although the Tutorial 1 case also throws sometimes an unrelated exception, which cause I did not figure out, it still seemed easier to reproduce on that project, because for GobPie to work Goblint must be installed prior as well (which takes a ton of time, but is still possible if needed).

**Comment by linghuiluo** [comment]
@karoliineh thanks for reporting this. I will take a look next days.

**Comment by linghuiluo** [comment]
The issue is fixed in the new release
```
 <dependency>
    <groupId>com.github.magpiebridge</groupId>
    <artifactId>magpiebridge</artifactId>
    <version>0.1.3</version>
</dependency>
```
