### ISSUE TITLE
WalaIRToJimpleConverter: If-statements missing jump target

### ISSUE THREAD

**Issue by SvenEV** [MagpieBridge/MagpieBridge#8]
In the following example, the generated Jimple if-statement has a target of `null`. This breaks the control flow and thus causes issues in various code analyses.

**Java:**
```Java
public static void repro() {
    if (true)
        return;
}
```

**Jimple:**
```Java
public static void repro()
{
    int $i0;
    if $i0 == 0 goto [?= null];
    return;
}
```

**Comment by linghuiluo** [comment]
this issue is fixed now, was not there when i implemented, it seemed my shk did some optimization which caused this issue
