### ISSUE TITLE
Impossible to know when MagpieServer is done running

### ISSUE THREAD

**Issue by liblit** [MagpieBridge/MagpieBridge#85]
After starting a MagpieBridge server using standard input and output, it is impossible to know when that server is done running. This makes it difficult to manage the life cycle of a MagpieBridge server as part of a larger system.

The core problem is that `MagpieServer.launchOnStdio` always returns immediately, even though the launched server continues running in the background. Furthermore, this method returns `void`, which gives the caller no handle by which to track the server's execution. I propose the following API changes:

1. `MagpieServer.launchOnStream` should return the `Future<Void>` provided by the `launcher.startListening()` call [here](https://github.com/MagpieBridge/MagpieBridge/blob/02322f148c8b6b74e5db77dc996f6ae2ae1c7679/src/main/java/magpiebridge/core/MagpieServer.java#L228).

1. `MagpieServer.launchOnStdio` should return the `Future<Void>` provided by the `launchOnStream(System.in, System.out)` call [here](https://github.com/MagpieBridge/MagpieBridge/blob/develop/src/main/java/magpiebridge/core/MagpieServer.java#L206).

Callers to `MagpieServer.launchOnStdio` can then wait on this returned `Future` to know when the server is done running. Conversely, existing MagpieBridge-based tools that were not expecting `MagpieServer.launchOnStdio` to return a value can simply ignore the `Future<Void>` that would be returned after this change. So this change seems reasonably backward-compatible.

**Comment by linghuiluo** [comment]
@liblit this change should be easy to make. But why do you say that it is impossible to know when the server is done running? According to the protocol the server is shut done when the client sends the [exit notification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#exit). The MagpieServer will [terminate the JVM when it handles the notification .](https://github.com/MagpieBridge/MagpieBridge/blob/02322f148c8b6b74e5db77dc996f6ae2ae1c7679/src/main/java/magpiebridge/core/MagpieServer.java#L528 )

**Comment by juliandolby** [comment]
I agree this change will not break anything, and it makes sense if it will solve your problem.  I guess the original motivation for MagpieBridge was IDE integration, and, with most LSP integrations into IDEs, the server gets shut down by the IDE, typically when it exits.  Perhaps you could describe your usage in a few words?

**Comment by liblit** [comment]
Oh, I did not realize that `MagpieServer` shuts down the entire JVM when the told to exit. I assumed that my own `public static void main` method should be responsible for exiting the JVM when appropriate. My mental model was that `MagpieServer.launchOnStdio` would either (1) return once the server is done running or (2) return a `Future` that I could wait for to determine that the server is done running.

I now understand that neither of those is the case. Rather, my `main` method should run to completion but should assume that the JVM itself will keep running until the LSP server is done. In my experience, that's unusual: I generally expect the `main` method call to have roughly the same life span as the entire JVM. But OK, I can cope with that not being the case here.
