### ISSUE TITLE
WalaIRToJimpleConverter: Wrong code generated for "if (true)"

### ISSUE THREAD

**Issue by SvenEV** [MagpieBridge/MagpieBridge#9]
For `if (true)` and `if (false)`, equivalent Jimple code is generated, causing `if (true)` to have the semantics of `if (false)`. It looks like an assignment `$i0 = 1;` is missing in the `if (true)` case.

Should there even be uninitialized local variables in Jimple?

**Java:**
```Java
private static void repro() {
    if (true) return;
    if (false) return;
    return;
}
```
**Jimple:**
```Java
private static void repro()
{
    int $i0, $i1;
    nop;
    if $i0 == 0 goto label1;
    return;
  label1:
    if $i1 == 0 goto label2;
    return;
  label2:
    return;
}
```

**Comment by linghuiluo** [comment]
this issue is tricky, because i don't get the assignment from wala.

**Comment by linghuiluo** [comment]
@juliandolby any ideas about this

**Comment by linghuiluo** [comment]
fixed
